
name: CI
on: 
  - push
  - workflow_dispatch

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        python -u build_package.py
      shell: cmd
    - uses: actions/upload-artifact@master
      with:
          name: dependencies
          path: build\dependencies.7z
